### PR TITLE
Adding ABI DSL Notes

### PR DESCRIPTION
**Pull request by nhanford**
I will probably need to iterate on the formatting.

### CODE REVIEW

**Comment by vsoch** [comment]
@nhanford ping me when you want a review!

**Comment by nhanford** [comment]
Finally got around to getting local testing working and the formatting looks decent.

**Comment by vsoch** [comment]
nice! I'm happy to merge if you've inspected locally and are happy too :)

**Comment by nhanford** [comment]
Yup I think you also gave me merge permissions, so if these changes and this workflow look okay I can probably just merge changes myself going forward. Sorry for the bumps in the road earlier.

**Comment by vsoch** [comment]
No need to apologize for anything @nhanford

**Pull request merged**
